import datetime
def erstellen (zeitStunden, zyklusGesamt, i, zyklusWasser, moistureLevel_1, moistureLevel_2, opVoltage, pumpenMessSpannung, sleepSensorGesamt, idleZeit, temperature):
   file = open("logfiles/Schattenspeicher_AutomaticProgram.txt", "w")
   file.write("--- Schattenspeicher Start ---\n")
   file.write("\n")
   file.write("Dieses file wird am Ende jedes Zyklus erzeugt.\n")
   file.write("Zyklus: Sensor-Monitoring + Schlafen (+ Pumpenansteuerung).\n")
   file.write("Sensor-Monitoring:\n")
   file.write(str(sleepSensorGesamt))
   file.write("s")
   file.write("\n")
   file.write("Schlafen:\n")
   file.write(str(idleZeit))
   file.write("s")
   file.write("\n")
   file.write("Letzte Speicherung:\n")
   file.write("{:%d.%m.%Y %H:%M:%S}".format(datetime.datetime.now()))
   file.write("\n\n")
   file.write("** Programm-Parameter **\n") 
   file.write("\n")
   file.write("Vorgabe Gesamtzeit durch das Programm:\n")
   file.write(str(zeitStunden))
   file.write("h")
   file.write("\n")
   file.write("Gesamtzyklen absolviert:\n")
   file.write(str(zyklusGesamt))
   file.write("\n")
   file.write("Somit Laufzeit absolviert (Pumpenansteuerungszeit wird nicht addiert):\n")
   file.write(str(i))
   file.write("s")
   file.write("\n")
   file.write("Zyklen mit Pumpenansteuerung (10s) absolviert:\n")
   file.write(str(zyklusWasser))
   file.write("\n")
   file.write("Letzte ermittelte Bodenfeuchte (Sensor 1):\n")
   file.write(str(int(moistureLevel_1)))
   file.write("%")
   file.write("\n")
   file.write("Letzte ermittelte Bodenfeuchte (Sensor 2):\n")
   file.write(str(int(moistureLevel_2)))
   file.write("%")
   file.write("\n\n")
   file.write("** Elektrische Überwachungen **\n")
   file.write("\n")
   file.write("OP-Eingangspannung (nichtinvertierend) bei letzter Pumpenansteuerung:\n")            
   file.write("{:>2.3f}".format(opVoltage))
   file.write(" V")
   file.write("\n")            
   file.write("Shunt-Spannung bei letzter Pumpenansteuerung (falls verwendet):\n")            
   file.write("{:>2.3f}".format(pumpenMessSpannung))
   file.write(" V")
   file.write("\n\n") 
   file.write("Beide Werte sind <0.01V WENN:\n")
   file.write("A. keine Pumpenansteuerung bisher (Initialwerte=0.0V)\n")
   file.write("ODER\n")
   file.write("B. Schwimmerschalter hat ausgelöst (wahrscheinlich)\n")
   file.write("ODER\n")
   file.write("C. elektrischem Problem auf dem Board")
   file.write("\n\n")
   file.write("Beide Werte sind >0.2V WENN:\n")
   file.write("Pumpenansteuerung erfolgt")
   file.write("\n\n")
   file.write("** Sonstiges **\n")
   file.write("\n")
   file.write("Temperatur:\n")
   file.write("{0:0.2f}".format(temperature))   
   file.write("°C")
   file.write("\n\n")
   file.write("--- Schattenspeicher Ende ---\n")
   file.close()  