import datetime
def erstellen (zeitStunden, zyklusGesamt, i, zyklusWasser, moistureLevel_1, moistureLevel_2, opVoltage, pumpenMessSpannung):
   file = open("logfiles/Schattenspeicher_nh.txt", "w")
   file.write("--- Schattenspeicher Start ---\n")
   file.write("\n")
   file.write("Dieses file wird am Ende jedes Zyklus erzeugt.\n")
   file.write("Zyklus: Monitoring (5s), Pumpenansteuerung(10s, optional), Schlafen (295s).\n")
   file.write("\n")
   file.write("Letzte Speicherung:\n")
   file.write("{:%d.%m.%Y %H:%M:%S}".format(datetime.datetime.now()))
   file.write("\n\n")
   file.write("** Programm-Parameter **\n") 
   file.write("\n")
   file.write("Vorgabe Gesamtzeit durch das Programm:\n")
   file.write(str(zeitStunden))
   file.write("h")
   file.write("\n")
   file.write("Gesamtzyklen absolviert:\n")
   file.write(str(zyklusGesamt))
   file.write("\n")
   file.write("Somit Laufzeit absolviert (Pumpenansteuerungszeit wird nicht addiert):\n")
   file.write(str(i))
   file.write("s")
   file.write("\n")
   file.write("Zyklen mit Pumpenansteuerung absolviert:\n")
   file.write(str(zyklusWasser))
   file.write("\n")
   file.write("Letzte ermittelte Bodenfeuchte (Sensor 1):\n")
   file.write(str(int(moistureLevel_1)))
   file.write("%")
   file.write("\n")
   file.write("Letzte ermittelte Bodenfeuchte (Sensor 2):\n")
   file.write(str(int(moistureLevel_2)))
   file.write("%")
   file.write("\n\n")
   file.write("** Elektrische Überwachungen **\n")
   file.write("\n")
   file.write("OP-Eingangspannung (nichtinvertierend) bei letzter Pumpenansteuerung:\n")            
   file.write("{:>2.3f}".format(opVoltage))
   file.write(" V")
   file.write("\n")            
   file.write("Shunt-Spannung bei letzter Pumpenansteuerung:\n")            
   file.write("{:>2.3f}".format(pumpenMessSpannung))
   file.write(" V")
   file.write("\n\n") 
   file.write("Beide Werte sind <0.01V WENN:\n")
   file.write("A. keine Pumpenansteuerung bisher (Initialwerte=0.0V)\n")
   file.write("ODER\n")
   file.write("B. Schwimmerschalter hat ausgelöst (wahrscheinlich)\n")
   file.write("ODER\n")
   file.write("C. elektrischem Problem auf dem Board (unwahrscheinlich)")
   file.write("\n\n")
   file.write("Beide Werte sind >0.2V WENN:\n")
   file.write("Pumpenansteuerung erfolgt\n")
   file.write("\n")
   file.write("--- Schattenspeicher Ende ---\n")
   file.close()  