#!/bin/bash
cd /home/pi/pico/pico-examples/build
export PICO_SDK_PATH=../../pico-sdk # kennzeichnet die Variable PICO_SDK_PATH als global mit dem Wert =../../pico-sdk
cmake ..
echo "Switch to '/home/pi/pico/pico-examples/build/...' (the project you wish to build) now"
echo "Then type 'make' to create the compiled file"
